name: arm-imm

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  DIY_P1_SH: configs/immortalwrt/diy-z1.sh
  DIY_P2_SH: configs/immortalwrt/diy-arm.sh
  TZ: Asia/Shanghai

jobs:
  build:
    name: Build imm (${{ matrix.name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 2512
            branch: openwrt-25.12
            feeds: configs/immortalwrt/feeds.conf.default
            config: configs/immortalwrt/build-arm.config

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL https://raw.githubusercontent.com/yunxi993/OpenWrt-Test/main/depends)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo -E timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Fast Free Space
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/share/boost /usr/share/swift /usr/share/sbt /usr/src/linux-headers*
        sudo docker image prune -a -f
        df -hT

    - name: Clone source code
      working-directory: ${{ github.workspace }}
      run: |
        git clone --depth 1 $REPO_URL -b ${{ matrix.branch }} openwrt
        ln -sf ${{ github.workspace }}/openwrt $GITHUB_WORKSPACE/openwrt

    - name: Cache Management
      uses: HiGarfield/cachewrtbuild@main
      with:
        ccache: true
        mixkey: ARM-${{ matrix.name }}
        prefix: ${{ github.workspace }}/openwrt

    - name: Load and Update feeds
      run: |
        [ -e ${{ matrix.feeds }} ] && mv ${{ matrix.feeds }} openwrt/feeds.conf.default
        chmod +x $DIY_P1_SH
        ./$DIY_P1_SH
        cd openwrt
        ./scripts/feeds update -a && ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e ${{ matrix.config }} ] && mv ${{ matrix.config }} openwrt/.config
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH

    - name: Download package
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j$(nproc)
        find dl -size -1024c -exec rm -f {} \;
        echo "FILE_DATE=$(date +"%Y-%m-%d_%H%M")" >> $GITHUB_ENV

    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        df -hT
        echo -e "$(($(nproc)+1)) thread compile"
        make -j$(($(nproc)+1)) || make -j1 V=s
        echo "ACT_DATE=$(date +"%Y-%m-%d %H%M")" >> $GITHUB_ENV
        echo "REL_DATE=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
        echo "TAG_DATE=$(date +"%m%d-%H%M%S")" >> $GITHUB_ENV
        #ls . && echo "----" && find . -type d -name "*-cache-openwrt*" && echo "----" && find . -type f -name "*-cache-openwrt*"
        df -hT

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Prepare artifact
      run: |
        mkdir -p openwrt/bin/package openwrt/bin/firmware
        TARGETS_DIR=openwrt/bin/targets/
        PACKAGE_DIR=openwrt/bin/package/
        FIRMWARE_DIR=openwrt/bin/firmware/
        PACKAGES_DIR=openwrt/bin/packages/
        # Cleanup metadata
        rm -rf $(find ${TARGETS_DIR} -name "packages" -o -name "*.buildinfo" -o -name "sha256sums" -o -name "*.manifest")
        # Organize files
        cp -rf $(find ${TARGETS_DIR} -type f) ${FIRMWARE_DIR}
        cp -rf $(find ${PACKAGES_DIR} -type f -name "*.apk") ${PACKAGE_DIR} || true
        cd ${PACKAGE_DIR}
        tar -zcvf IPK.tar.gz *
        mv -f IPK.tar.gz ../

    - name: Deliver package
      uses: actions/upload-artifact@main
      with:
        name: ${{ matrix.name }}-IPK
        path: ./openwrt/bin/package/

    - name: Deliver firmware
      uses: actions/upload-artifact@main
      with:
        name: ${{ matrix.name }}-firmware
        path: ./openwrt/bin/firmware/

    - name: Package Armvirt (Flippy)
      uses: ophub/flippy-openwrt-actions@main
      env:
        OPENWRT_ARMVIRT: openwrt/bin/targets/*/*/*.tar.gz
        KERNEL_REPO_URL: https://github.com/yunxi993/OpenWrt-Test/releases/tag/kernel_stable
        PACKAGE_SOC: s905d
        KERNEL_AUTO_LATEST: true
        KERNEL_VERSION_NAME: 6.12.16_6.18.19
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WHOAMI: Sil

    - name: copy update files
      run: |
        PACKIT_DIR=/opt/openwrt_packit
        OPENWRT_BIN_DIR=$GITHUB_WORKSPACE/openwrt/bin/
        cp ${PACKIT_DIR}/files/update-amlogic-openwrt.sh ${PACKIT_DIR}/output/
        rm -rf $(find ${PACKIT_DIR}/output/ -name "sha256sums" -o -name "*.gz.sha" -o -name "*.tar.gz")
        cp ${OPENWRT_BIN_DIR}IPK.tar.gz ${PACKIT_DIR}/output/

    - name: Upload OpenWrt Firmware to Release
      uses: ncipollo/release-action@main
      with:
        name: ARM_Imm ${{ env.REL_DATE }}
        tag: ${{ env.TAG_DATE }}
        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          ## Firmware for personal use, plug-ins can be deleted according to personal needs.
          - **Devices:** Phicomm N1
          - **Branches:** ${{ matrix.branch }}
          - **Default IP:** 192.168.11.11
          - **Username:** `root`
