name: x86-build

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/openwrt/openwrt
  DIY_P1_SH: configs/official/diy-z1.sh
  DIY_P2_SH: configs/official/diy-x86.sh
  TZ: Asia/Shanghai

jobs:
  build:
    name: Build x86 (${{ matrix.name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: main
            branch: main
            feeds: configs/official/feeds.main
            config: configs/official/x86-main.config
          - name: 2512
            branch: openwrt-25.12
            feeds: configs/official/feeds.2512
            config: configs/official/x86-2512.config

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker image prune -f
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL https://raw.githubusercontent.com/yunxi993/OpenWrt-Test/main/depends)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo -E timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        df -hT

    - name: Free up space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Clone source code
      working-directory: ${{ github.workspace }}
      run: |
        git clone --depth 1 --single-branch $REPO_URL -b ${{ matrix.branch }} openwrt
        ln -sf ${{ github.workspace }}/openwrt $GITHUB_WORKSPACE/openwrt

    - name: Cache Management
      uses: HiGarfield/cachewrtbuild@main
      with:
        ccache: true
        mixkey: x86-${{ matrix.name }}
        prefix: ${{ github.workspace }}/openwrt

    - name: Load and Update feeds
      run: |
        [ -e ${{ matrix.feeds }} ] && mv ${{ matrix.feeds }} openwrt/feeds.conf.default
        chmod +x $DIY_P1_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH
        ./scripts/feeds update -a && ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e ${{ matrix.config }} ] && mv ${{ matrix.config }} openwrt/.config
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH

    - name: Download package
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j$(nproc)
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        df -hT
        echo -e "$(($(nproc)+1)) thread compile"
        make -j$(($(nproc)+1)) || make -j1 V=s
        echo "ACT_DATE=$(date +"%Y-%m-%d %H%M")" >> $GITHUB_ENV
        echo "REL_DATE=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
        echo "TAG_DATE=$(date +"%m%d-%H%M%S")" >> $GITHUB_ENV
        #ls . && echo "----" && find . -type d -name "*-cache-openwrt*" && echo "----" && find . -type f -name "*-cache-openwrt*"
        df -hT

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Prepare artifact
      run: |
        FIRMWARE_DIR="openwrt/bin/firmware"
        PACKAGE_DIR="openwrt/bin/package"
        TARGETS_DIR="openwrt/bin/targets"
        PACKAGES_DIR="openwrt/bin/packages"
        mkdir -p "$FIRMWARE_DIR" "$PACKAGE_DIR" "$PACKAGES_DIR"
        find "$TARGETS_DIR" -type f \( -name "packages" -o -name "*.buildinfo" -o -name "sha256sums" -o -name "*.manifest" \) -delete
        KVER=$(ls openwrt/target/linux/generic/kernel-* | sort -V | tail -n 1)
        KVER=$(grep 'LINUX_VERSION' "$KVER" | awk -F '[-= ]+' '{print $2$3}' | tr -d ' ')
        find "$TARGETS_DIR" -type f -name "*efi*" -exec mv -f {} "${FIRMWARE_DIR}/openwrt-${{ matrix.name }}-"$KVER"-x86-64-generic-squashfs-combined-efi.img.gz" \;
        find "$PACKAGES_DIR" -type f -name "*.apk" -exec mv -t "$PACKAGE_DIR" {} +
        (cd "$PACKAGE_DIR" && tar -zcvf ${{ matrix.name }}-IPK.tar.gz * && rm -rf *.apk)

    - name: Deliver package
      uses: actions/upload-artifact@main
      with:
        name: ${{ matrix.name }}-IPK
        path: ./openwrt/bin/package/

    - name: Deliver firmware
      uses: actions/upload-artifact@main
      with:
        name: ${{ matrix.name }}-firmware
        path: ./openwrt/bin/firmware/

  upload-release:
    name: Upload to Release
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Download Artifacts
      uses: actions/download-artifact@main
      with:
        path: ./downfiles
        merge-multiple: true

    - name: Organize Release Files
      run: |
        mkdir -p ./combined-firmware
        find ./downfiles/ -type f \( -name "*efi*" -o -name "*.gz" \) -exec mv -t ./combined-firmware/ {} +
        echo "REL_DATE=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
        echo "TAG_DATE=$(date +"%m%d-%H%M%S")" >> $GITHUB_ENV

    - name: Upload Firmware to Release
      uses: ncipollo/release-action@main
      with:
        name: x86_64 ${{ env.REL_DATE }}
        tag: ${{ env.TAG_DATE }}
        artifacts: ./combined-firmware/*
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          ## Firmware for personal use, plug-ins can be deleted according to personal needs.
          - **Devices:** x86_64
          - **Branches:** main, openwrt-25.12
          - **Default IP:** `192.168.11.13`
          - **Username:** `root`
